name: Schedule Spring Services

on:
  schedule:
    # The cron syntax is based on UTC time
    - cron: '0 23 * * *'   # This runs at 11:00 PM UTC
    - cron: '0 7 * * *'     # This runs at 7:00 AM UTC

jobs:
  stop_services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install requests
        run: pip install requests
        
      - name: Run script to stop services
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}  # Use secret for API token
          SERVICE_ID_1: ${{ secrets.SERVICE_ID_1 }}        # Use secret for Service ID 1
          SERVICE_ID_2: ${{ secrets.SERVICE_ID_2 }}        # Use secret for Service ID 2
        run: python service_control.py stop

  start_services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install requests
        run: pip install requests
        
      - name: Run script to start services
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}  # Use secret for API token
          SERVICE_ID_1: ${{ secrets.SERVICE_ID_1 }}        # Use secret for Service ID 1
          SERVICE_ID_2: ${{ secrets.SERVICE_ID_2 }}        # Use secret for Service ID 2
        run: python service_control.py start
